version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  geoapi:
    depends_on:
      - "elasticsearch"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - dockerapi-dev  
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    ports:
      - "9200:9200"
    restart: always
    volumes:
      - db_volume:/usr/share/elasticsearch/data
    environment:
      discovery.type: "single-node"
    networks:
      - dockerapi-dev

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.1
    ports:
      - "5601:5601"
    networks:
      - dockerapi-dev

volumes:
  db_volume:
         
    
     